[tasks.hot]
run_task = { name = ["build", "move-bin"] }

[tasks.move-bin]
script = [
'''
cp ./target/release/upver ./bin/
'''
]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

run_task = { name = ["build-musl", "move-bin-musl"] }


[tasks.release-musl]
script = [
'''
cross build --target x86_64-unknown-linux-musl --release
cp target/x86_64-unknown-linux-musl/release/upver ./bin/musl
'''
]
