name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup MUSL
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          make release_linux
          # cargo build --locked --release --target=x86_64-unknown-linux-musl
          # zip -j ${BIN_NAME}-v${VERSION}-x86_64-linux.zip target/x86_64-unknown-linux-musl/release/${BIN_NAME}
      - name: Build for macOS
        if: matrix.os == 'macOS-latest'
        run: |
          make release_mac
          # cargo build --locked --release --target=x86_64-apple-darwin
          # zip -j ${BIN_NAME}-v${VERSION}-x86_64-mac.zip target/x86_64-apple-darwin/release/${BIN_NAME}
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          make release_win
          # cargo build --locked --release --target=x86_64-pc-windows-msvc
          # 7z a ${BIN_NAME}-v${VERSION}-x86_64-win.zip target/x86_64-pc-windows-msvc/release/${BIN_NAME}.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "[Changelog](https://github.com/dalance/procs/blob/master/CHANGELOG.md)"
          files: "*.zip\n*.rpm"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
