name: upver

on:
  pull_request:
    branches:
      - alpha
    types: [closed]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: alpha
      - uses: actions/checkout@v2
        with:
          repository: fuyutarow/upver
          path: upver
      - name: update version
        run: upver/bin/musl/upver up -rz Cargo.toml
      - name: commit
        run: |
          cd main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "[GitHub Actions] Update version"
          git push
