name: upver

on:
  pull_request:
    branches:
      - alpha
    types: [closed]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v2
      - name: Checkout fuyutarow/upver as a CI tool
        uses: actions/checkout@v2
        with:
          repository: fuyutarow/upver
          path: upver
      - name: Update version
        run: upver/bin/musl/upver up -rz Cargo.toml
      - name: Commit your repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "[GitHub Actions] Update version"
          git push
